services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: workme-backend
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - workme-db

  workme-db:
    image: postgres:15
    container_name: workme-db
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
